import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_UK': {
          'titleGraphs': 'Graphs',
          'titleOrders': 'Orders',
          'titleLogin': 'Login',
          'buttonLogin': 'Login',
          'buttonUpdate': 'Update',
          'titleMenu': 'Menu',
          'titleEmployees': 'Employees',
          'titleEmployee': 'Employee',
          'titleDashboard': 'Dashboard',
          'titleSettings': 'Settings',
          'nightMode': 'Night Mode',
          'changeLanguage': 'Change Language',
          'today': 'Today',
          'thisWeek': 'This Week',
          'thisMonth': 'This Month',
          'app': 'App',
          'welcome': 'Welcome',
          'restaurantInformations': 'Restaurant Informations:',
          'numberOfTables': 'Number of Tables',
          'table': 'Table',
          'cancel': 'Cancel',
          'totalEmployees': 'Total Employees',
          'supervisors': 'Supervisors',
          'roomAttendants': 'Room Attendants',
          'kitchenAttendants': 'Kitchen Attendants',
          'roomAttendant': 'Room Attendant',
          'kitchenAttendant': 'Kitchen Attendant',
          'ordersOfThisMonth': 'Orders of This Month',
          'ordersOfThisYear': 'Orders of This Year',
          'salesForThisMonth': 'Sales for This Month',
          'salesForThisYear': 'Sales for This Year',
          'email': 'Email',
          'password': 'Password',
          'forgotPassword': 'Forgot the password? ',
          'clickHere': 'Click Here!',
          'supervisor': 'Supervisor',
          'nameAndSurname': 'Name and Surname',
          'role': 'Role',
          'search': 'Search',
          'viewPerformance': 'View Performance',
          '+': '+',
          'add': 'Add',
          'sections': 'Sections',
          'dishes': 'Dishes',
          'id': 'ID',
          'date': 'Date',
          'or': 'or',
          'status': 'Status',
          'name': 'Name',
          'surname': 'Surname',
          'assumptionDate': 'Assumption Date',
          'amount': 'Amount',
          'completionTime': 'Completion Time',
          'account': 'Change Password',
          'oldPassword': 'Old Password',
          'newPassword': 'New Password',
          'confirmPassword': 'Confirm Password',
          'logout': 'Logout',
          'italian': 'Italian',
          'english': 'English',
          'dishName': 'Dish Name',
          'price': 'Price',
          'description': 'Description',
          'allergens': 'Allergens',
          'titleOrder': 'Order',
          'requiredPassword': 'Password is required! ',
          'lengthPassword': 'Password length must be less than 12 characters!',
          'mustPassword': 'Password must contain characters and numbers!',
          'mustEmail': 'Value must be an email address!',
          'requiredEmail': 'Email is required!',
          'connectionRefused': 'Cannot connect to the server.',
          'orderInProgress': 'Order in Progress',
          'passwordRecovery': 'Password Recovery',
          'send': 'Send',
          'addDish': 'Add Dish',
          'addSection': 'Add Section',
          'section': 'Section',
          'dish': 'Dish',
          'tutorialMenu':
              'To get started, add a Section or Dish, or select a plate to edit it!',
          'tutorialCook':
              'Swipe left on an order to process it and right to cancel it!',
          'to': 'to ',
          'dateSelect': 'Analyze the period from ',
          'selectEmployee': 'Select an Employee ',
          'tableSelect': 'Select a table ',
          'select': 'Select',
          'tutorialOrder': 'Swipe right on a dish to cancel it!',
        },
        'it_IT': {
          'tutorialOrder': 'Swipe a destra su un piatto per eliminarlo!',
          'select': 'Seleziona',
          'tableSelect': 'Seleziona un Tavolo ',
          'selectEmployee': 'Seleziona un dipendente ',
          'to': 'al ',
          'dateSelect': 'Analizza il periodo che va dal ',
          'titleGraphs': 'Grafici',
          'orderInProgress': 'Ordini in Lavorazione',
          'connectionRefused': 'Non è possibile connettersi al server.',
          'requiredPassword': 'La password è necessaria! ',
          'lengthPassword': 'La password deve essere massimo 12 caratteri!',
          'mustPassword': 'La password deve contenere numeri e lettere!',
          'mustEmail': 'Il campo deve essere un valore email valido!',
          'requiredEmail': 'L\'email è necessaria!',
          'titleOrders': 'Ordini',
          'titleLogin': 'Login',
          'titleEmployee': 'Dipendente',
          'buttonLogin': 'Accedi',
          'add': 'Aggiungi',
          'buttonUpdate': 'Aggiorna',
          'titleMenu': 'Menu',
          'cancel': 'Annulla',
          'titleEmployees': 'Dipendenti',
          'titleDashboard': 'Dashboard',
          'titleSettings': 'Impostazioni',
          'nightMode': 'Modalità Notturna',
          'changeLanguage': 'Cambia Lingua',
          'today': 'Odierni',
          'thisWeek': 'Di Questa Settimana',
          'thisMonth': 'Di Questo Mese',
          'app': 'App',
          'welcome': 'Benvenuto',
          'restaurantInformations': 'Informazioni Ristorante:',
          'numberOfTables': 'Numero di Tavoli',
          'table': 'Tavolo',
          'totalEmployees': 'Dipendenti Totali',
          'supervisors': 'Supervisori',
          'supervisor': 'Supervisore',
          'roomAttendants': 'Addetti Sala',
          'kitchenAttendants': 'Addetti Cucina',
          'roomAttendant': 'Addetto Sala',
          'kitchenAttendant': 'Addetto Cucina',
          'ordersOfThisMonth': 'Ordini di questo mese',
          'ordersOfThisYear': 'Ordini di quest\'anno',
          'salesForThisMonth': 'Vendite di questo mese',
          'salesForThisYear': 'Vendite di quest\'anno',
          'email': 'Email',
          'password': 'Password',
          'forgotPassword': 'Hai dimenticato la password? ',
          'clickHere': 'Clicca qui!',
          'nameAndSurname': 'Nome e Cognome',
          'name': 'Nome',
          'surname': 'Cognome',
          'role': 'Ruolo',
          'search': 'Cerca',
          'viewPerformance': 'Visualizza Rendimento',
          '+': '+',
          'sections': 'Sezioni',
          'dishes': 'Piatti',
          'id': 'ID',
          'date': 'Data',
          'or': 'oppure',
          'status': 'Status',
          'assumptionDate': 'Data di Assunzione',
          'amount': 'Importo',
          'completionTime': 'Tempo di Completamento',
          'account': 'Cambia Password',
          'oldPassword': 'Vecchia Password',
          'newPassword': 'Nuova Password',
          'confirmPassword': 'Conferma Password',
          'logout': 'Logout',
          'italian': 'Italiano',
          'english': 'Inglese',
          'dishName': 'Nome Piatto',
          'price': 'Prezzo',
          'description': 'Descrizione',
          'allergens': 'Allergeni',
          'titleOrder': 'Ordine',
          'passwordRecovery': 'Recupera Password',
          'send': 'Invia',
          'addDish': 'Aggiungi Piatto',
          'addSection': 'Aggiungi Sezione',
          'section': 'Sezione',
          'dish': 'Piatto',
          'tutorialMenu':
              'Per iniziare, aggiungi una Sezione o un Piatto, oppure seleziona un piatto per modificarlo!',
          'tutorialCook':
              'Swipe a sinistra su un ordine per evaderlo ed a destra per annullarlo!'
        }
      };
}
