// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6SQPK-niTueTEBgZ44YZfYp8bMXW3AkU',
    appId: '1:375245860765:web:27ea899ae96d64ea918974',
    messagingSenderId: '375245860765',
    projectId: 'ratatouille23-ccbe5',
    authDomain: 'ratatouille23-ccbe5.firebaseapp.com',
    storageBucket: 'ratatouille23-ccbe5.appspot.com',
    measurementId: 'G-NZ9H3V8NJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdfJoIKaEbEhPmhYcQx3kMb-ty1pr08Sk',
    appId: '1:375245860765:android:e04e640cc4aef6d5918974',
    messagingSenderId: '375245860765',
    projectId: 'ratatouille23-ccbe5',
    storageBucket: 'ratatouille23-ccbe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKIu6_D7PPuKHTPy_B_KQWRcwpbkEDg4k',
    appId: '1:375245860765:ios:298d36117a6869e2918974',
    messagingSenderId: '375245860765',
    projectId: 'ratatouille23-ccbe5',
    storageBucket: 'ratatouille23-ccbe5.appspot.com',
    iosBundleId: 'com.example.ratatouille23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKIu6_D7PPuKHTPy_B_KQWRcwpbkEDg4k',
    appId: '1:375245860765:ios:298d36117a6869e2918974',
    messagingSenderId: '375245860765',
    projectId: 'ratatouille23-ccbe5',
    storageBucket: 'ratatouille23-ccbe5.appspot.com',
    iosBundleId: 'com.example.ratatouille23',
  );
}
